/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_probedroid_Instrument */

#ifndef _Included_org_probedroid_Instrument
#define _Included_org_probedroid_Instrument
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_probedroid_Instrument
 * Method:    instrumentMethodNative
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Lorg/probedroid/support/MethodBundle;)V
 */
JNIEXPORT void JNICALL Java_org_probedroid_Instrument_instrumentMethodNative
  (JNIEnv *, jobject, jstring, jstring, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
